
//Minumum Threshold = 1000
//Date Range = 2025-10-01 to 2026-01-04
//File generated on 2026-01-05
//Excluded RSIDs: AdobeUsageAnalytics, SquadIntel, WebSDKTest, AAConnector, GLOBALDEVELOPMENTREPORTSUITE
const botInvestigationMinThresholdVisits = [
    'Apuestasdeportivascom',
    'Betca',
    'Blackjackcom',
    'Cardschatcom',
    'CasinoEnligneca',
    'CasinoOnlinecouk',
    'CasinoOnlinede',
    'CasinoOnlinenl',
    'CasinoSpielede',
    'Casinoat',
    'Casinoca',
    'Casinoch',
    'Casinocl',
    'Casinocombr',
    'Casinoconz',
    'Casinocouk',
    'Casinocoza',
    'Casinoit',
    'Casinomx',
    'Casinoonlinecom',
    'Casinoorg',
    'Casinope',
    'Casinous',
    'GuruDE',
    'GuruES',
    'GuruIT',
    'GuruJP',
    'GuruMain',
    'GuruOther',
    'GuruPT',
    'GuruSE',
    'MarcadoresOnlinecom',
    'MoneyPillar',
    'Oddspediacom',
    'OnlineBettingcom',
    'OnlineBlackjackca',
    'OnlineCasinoat',
    'OnlineCasinoca',
    'OnlineCasinoconz',
    'OnlineCasinocouk',
    'OnlineCasinocoza',
    'OnlineCasinoie',
    'OnlineCasinoscom',
    'OnlineCasinosde',
    'OnlineCasinosus',
    'OnlineGamblingca',
    'OnlineRouletteca',
    'OnlineRoulettecom',
    'OnlineSlotsca',
    'OnlineSlotscom',
    'Pokerde1stSite',
    'Pokersitescom',
    'Roulettecom',
    'Spielautomatende',
    'SportsBookReviewcom',
    'Sportsde',
    'coverscom',
    'elcomparadorcom'
];

            module.exports = botInvestigationMinThresholdVisits;