const StringsForCountries = [
  'Casinoorg-United States-FullRun',
  'Casinoorg-Canada-FullRun',
  'Casinoorg-Germany-FullRun',
  'Casinoorg-United Kingdom-FullRun',
  'Casinoorg-France-FullRun',
  'Casinoorg-Australia-FullRun',
  'Casinoorg-Philippines-FullRun',
  'Casinoorg-Spain-FullRun',
  'Casinoorg-Netherlands-FullRun',
  'Casinoorg-Bangladesh-FullRun',
  'Casinoorg-India-FullRun',
  'Casinoorg-Brazil-FullRun,',
  // 'SportsBookReviewcom-United States',
  // 'SportsBookReviewcom-Canada',
  // 'SportsBookReviewcom-Taiwan region',
  // 'SportsBookReviewcom-United Kingdom',
  // 'SportsBookReviewcom-Australia',
  // 'SportsBookReviewcom-Sweden',
  // 'SportsBookReviewcom-Mexico',
  // 'SportsBookReviewcom-Germany',
  // 'SportsBookReviewcom-Philippines',
  // 'SportsBookReviewcom-India',
  // 'SportsBookReviewcom-France',
  // 'SportsBookReviewcom-Brazil',
  // 'coverscom-United States',
  // 'coverscom-Canada',
  // 'coverscom-Venezuela',
  // 'coverscom-Dominican Republic',
  // 'coverscom-Mexico',
  // 'coverscom-Philippines',
  // 'coverscom-Sweden',
  // 'coverscom-South Korea',
  // 'coverscom-Australia',
  // 'coverscom-Taiwan region',
  // 'coverscom-United Kingdom',
  // 'coverscom-Chile',
  // 'Money Pillar-United States',
  // 'Money Pillar-Canada',
  // 'Money Pillar-Singapore',
  // 'Money Pillar-Malaysia',
  // 'Money Pillar-United Kingdom',
  // 'Money Pillar-New Zealand',
  // 'Money Pillar-Philippines',
  // 'Money Pillar-Ireland',
  // 'Money Pillar-Mexico',
  // 'Money Pillar-Germany',
  // 'Money Pillar-India',
  // 'Money Pillar-Australia',

  // 'Oddspediacom-United States',
  // 'Oddspediacom-Brazil',
  // 'Oddspediacom-Italy',
  // 'Oddspediacom-Mexico',
  // 'Oddspediacom-Spain',
  // 'Oddspediacom-Nigeria',
  // 'Oddspediacom-Peru',
  // 'Oddspediacom-Kenya',
  // 'Oddspediacom-United Kingdom',
  // 'Oddspediacom-South Africa',
  // 'Oddspediacom-Germany',
  // 'Oddspediacom-United Arab Emirates',

  // 'Cardschatcom-United States',
  // 'Cardschatcom-Canada',
  // 'Cardschatcom-Ukraine',
  // 'Cardschatcom-United Kingdom',
  // 'Cardschatcom-Australia',
  // 'Cardschatcom-Argentina',
  // 'Cardschatcom-Thailand',
  // 'Cardschatcom-Germany',
  // 'Cardschatcom-Romania',
  // 'Cardschatcom-India',
  // 'Cardschatcom-France',
  // 'Cardschatcom-Brazil',

];

module.exports = StringsForCountries